version: "3.4"
volumes:
  cache:
services:
  shekels:
    container_name: shekels
    image: shekels
    build:
      context: .
      dockerfile: shekels.dockerfile
    ports:
      - "9014:8888"
      - "8080:8080"
    userns_mode: "host"
    user: ubuntu
    volumes:
      - ../resources:/mnt/storage
      - ../:/home/ubuntu/shekels
      - ./jupyter:/home/ubuntu/.jupyter
      - ./ipython:/home/ubuntu/.ipython
      - ../artifacts:/tmp/dash_artifacts
      - ~/.ssh:/home/ubuntu/.ssh
    working_dir: "/home/ubuntu/shekels/python"
    command: "tail -f /dev/null"
