version: "3.4"
volumes:
  cache:
services:
  shekels:
    container_name: shekels
    image: shekels
    build:
      context: .
      dockerfile: shekels.dockerfile
    ports:
      - "9014:9000"
      - "5014:5014"
    userns_mode: "host"
    user: root
    volumes:
      - ../resources:/mnt/storage
      - ../:/root/shekels
      - ./jupyter:/root/.jupyter
      - ./ipython:/root/.ipython
      - ../artifacts:/tmp/dash_artifacts
      - ~/.ssh:/root/.ssh
    working_dir: "/root/shekels/python"
    command: "tail -f /dev/null"
