version: "3.8"
services:
  shekels:
    container_name: shekels
    image: shekels:dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "1000:9000"
      - "1080:8080"
    userns_mode: "host"
    user: ubuntu
    volumes:
      - ../:/home/ubuntu/shekels
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
      - ../artifacts:/tmp/dash_artifacts
      - ../resources:/mnt/storage
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
