version: "3.4"
volumes:
  cache:
services:
  shekels_prod:
    container_name: shekels-prod
    image: shekels-prod
    build:
      context: .
      dockerfile: shekels_prod.dockerfile
    ports:
      - "5015:80"
    userns_mode: "host"
    user: root
    volumes:
      - /tmp/shekels:/mnt/storage
      - ../:/root/shekels
    command: "tail -f /dev/null"
