kind: Namespace
apiVersion: v1
metadata:
  name: shekels

---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: shekels
    namespace: shekels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shekels
  template:
    metadata:
      labels:
        app: shekels
    spec:
      containers:
        - name: shekels
          image: thenewflesh/shekels:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: storage
              mountPath: /mnt/storage
      volumes:
        - name: storage
          hostPath:
            path: /Users/alex/Desktop/shekels_kubernetes/storage
            type: Directory

---
kind: Service
apiVersion: v1
metadata:
  name: shekels
  namespace: shekels
spec:
  type: ClusterIP
  selector:
    app: shekels
  ports:
    - port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: shekels
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: "1"
              memory: 2Gi

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  namespace: shekels
spec:
  rules:
  - host: shekels.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: shekels
            port:
              number: 80
